menu:
  #Home: /
  #Archives: /archives
  Home: /
  Archives: /archives
  About: /about

widgets:
- category
- tagcloud
- calendar
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-56580524-1
rss: /atom.xml

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
